version: '3.8'

services:
  server:
    build:
      context: server/
      dockerfile: dockerfile
    ports: 
      - "3001:3001"
    env_file:
      - server/.env

  client:
    build:
      context: client/
      dockerfile: dockerfile
    ports: 
      - "3000:3000"
    env_file:
      - client/.env
  
