FROM golang:1.24.6-alpine3.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /app/server-app .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server-app /server-app

EXPOSE 3001

CMD ["/server-app"]